-- 删除现有表（如果存在）
DROP TABLE IF EXISTS "OSINT Workstation";
DROP TABLE IF EXISTS rss_sources;

-- 创建文章表
CREATE TABLE "OSINT Workstation" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" TEXT,
  "Original_Article_Link" TEXT UNIQUE,
  "Description" TEXT,
  "Publication_Date" TIMESTAMP WITH TIME ZONE,
  "Source_Language" TEXT DEFAULT 'auto',
  "Fetch_Time" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "InfoSource" TEXT,
  "Vertical_Name" TEXT,
  "Processing_Flag" TEXT DEFAULT 'yes',
  "AI_Processing_Status" TEXT DEFAULT 'Not_Started',
  "Dify_Output_1" TEXT,
  "Dify_Output_2" TEXT,
  "Dify_Output_3" TEXT,
  "Google_Doc_URL" TEXT,
  "Manual_Review_Status" TEXT DEFAULT 'Not_Reviewed',
  "Notes_Action_Items" TEXT,
  "Notes" TEXT,
  "Last_Updated" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "is_selected" BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建RSS源管理表
CREATE TABLE rss_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  fetch_interval_hours INTEGER DEFAULT 24,
  last_fetch_time TIMESTAMP WITH TIME ZONE,
  fetch_time_of_day TIME DEFAULT '09:00:00',
  vertical_name TEXT,
  source_language TEXT DEFAULT 'en_US',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 插入RSS源数据
INSERT INTO rss_sources (name, url, description, is_active, vertical_name, source_language) VALUES
('3D Print 英文', 'https://news.google.com/rss/search?q=3D%2BPrint&hl=en-US&gl=US&ceid=US:en-US', '3D打印相关新闻', true, '3D Print 英文', 'en_US'),
('SEO英文', 'https://news.google.com/rss/search?q=SEO&hl=en-US&gl=US&ceid=US:en-US', 'SEO相关新闻', true, 'SEO英文', 'en_US'),
('AgriTech', 'https://news.google.com/rss/search?q=AgriTech&hl=en-US&gl=US&ceid=US:en-US', '农业科技相关新闻', true, 'AgriTech', 'en_US'),
('Smart Agriculture', 'https://news.google.com/rss/search?q=Smart%2BAgriculture&hl=en-US&gl=US&ceid=US:en-US', '智慧农业相关新闻', true, 'Smart Agriculture', 'en_US'),
('additivemanufacturing 英文', 'https://news.google.com/rss/search?q=additivemanufacturing&hl=en-US&gl=US&ceid=US:en-US', '增材制造相关新闻', true, 'additivemanufacturing 英文', 'en_US');

-- 关闭RLS（行级安全）
ALTER TABLE "OSINT Workstation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE rss_sources DISABLE ROW LEVEL SECURITY;

-- 创建索引
CREATE INDEX idx_osint_workstation_link ON "OSINT Workstation"("Original_Article_Link");
CREATE INDEX idx_osint_workstation_vertical ON "OSINT Workstation"("Vertical_Name");
CREATE INDEX idx_osint_workstation_status ON "OSINT Workstation"("AI_Processing_Status");
CREATE INDEX idx_rss_sources_active ON rss_sources(is_active);
CREATE INDEX idx_rss_sources_fetch_time ON rss_sources(last_fetch_time);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_osint_workstation_updated_at BEFORE UPDATE
    ON "OSINT Workstation" FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_rss_sources_updated_at BEFORE UPDATE
    ON rss_sources FOR EACH ROW EXECUTE FUNCTION update_updated_at();