-- 删除现有的RSS源表（如果存在）
DROP TABLE IF EXISTS rss_sources;

-- 创建RSS源管理表
CREATE TABLE rss_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  fetch_interval_hours INTEGER DEFAULT 24,
  last_fetch_time TIMESTAMP WITH TIME ZONE,
  fetch_time_of_day TIME DEFAULT '09:00:00',
  vertical_name TEXT,
  source_language TEXT DEFAULT 'en_US',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 批量导入你的RSS源
INSERT INTO rss_sources (name, url, description, is_active, vertical_name, source_language, fetch_interval_hours, fetch_time_of_day) VALUES
-- 启用的源
('3D Print 英文', 'https://news.google.com/rss/search?q=3D%2BPrint&hl=en-US&gl=US&ceid=US:en-US', '3D打印相关新闻', true, '3D Print 英文', 'en_US', 24, '09:00:00'),
('additivemanufacturing 英文', 'https://news.google.com/rss/search?q=additivemanufacturing&hl=en-US&gl=US&ceid=US:en-US', '增材制造相关新闻', true, 'additivemanufacturing 英文', 'en_US', 24, '09:30:00'),
('GEO英文', 'https://news.google.com/rss/search?q=SEO%2BGEO&hl=en-US&gl=US&ceid=US:en-US', 'SEO和地理位置相关新闻', true, 'GEO英文', 'en_US', 24, '10:00:00'),
('Smart Agriculture', 'https://news.google.com/rss/search?q=Smart%2BAgriculture&hl=en-US&gl=US&ceid=US:en-US', '智慧农业相关新闻', true, 'Smart Agriculture', 'en_US', 24, '10:30:00'),
('AgriTech', 'https://news.google.com/rss/search?q=AgriTech&hl=en-US&gl=US&ceid=US:en-US', '农业科技相关新闻', true, 'AgriTech', 'en_US', 24, '11:00:00'),
('Agricultural Robotics', 'https://news.google.com/rss/search?q=Agricultural%2BRobotics&hl=en-US&gl=US&ceid=US:en-US', '农业机器人相关新闻', true, 'Agricultural Robotics', 'en_US', 24, '11:30:00'),

-- 暂时禁用的源（根据你的表格，这些IsEnabled为空）
('SEO英文', 'https://news.google.com/rss/search?q=SEO&hl=en-US&gl=US&ceid=US:en-US', 'SEO相关新闻', false, 'SEO英文', 'en_US', 24, '08:00:00'),
('Y Combinator', 'https://news.google.com/rss/search?q=Y%2BCombinator&hl=en-US&gl=US&ceid=US:en-US', 'Y Combinator相关新闻', false, 'Y Combinator', 'en_US', 24, '08:30:00');

-- 创建索引
CREATE INDEX idx_rss_sources_active ON rss_sources(is_active);
CREATE INDEX idx_rss_sources_fetch_time ON rss_sources(last_fetch_time);
CREATE INDEX idx_rss_sources_vertical ON rss_sources(vertical_name);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_rss_sources_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_rss_sources_updated_at BEFORE UPDATE
    ON rss_sources FOR EACH ROW EXECUTE FUNCTION update_rss_sources_updated_at();