-- 🔥 简化版Supabase定时任务设置
-- 在Supabase SQL Editor中执行

-- 第1步：启用pg_cron扩展
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- 第2步：清理现有任务
SELECT cron.unschedule('rss-fetch-daily') WHERE EXISTS (
    SELECT 1 FROM cron.job WHERE jobname = 'rss-fetch-daily'
);

-- 第3步：创建简单的定时任务
-- 每天上午9点（UTC+8 = UTC 1:00）执行
SELECT cron.schedule(
    'rss-fetch-daily',
    '0 1 * * *',
    $$
    INSERT INTO cron_rss_logs (job_name, status, message) 
    VALUES ('rss-fetch-daily', 'triggered', 'Daily RSS fetch triggered at ' || NOW());
    $$
);

-- 第4步：创建日志表
CREATE TABLE IF NOT EXISTS cron_rss_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name TEXT,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT,
    message TEXT
);

-- 第5步：验证定时任务
SELECT 
    jobname,
    schedule,
    active,
    command
FROM cron.job 
WHERE jobname = 'rss-fetch-daily';

-- 第6步：手动测试
INSERT INTO cron_rss_logs (job_name, status, message) 
VALUES ('manual-test', 'success', 'Manual test at ' || NOW());

-- 查看日志
SELECT * FROM cron_rss_logs ORDER BY executed_at DESC LIMIT 5;

-- 完成提示
SELECT '✅ 基础定时任务已设置！' as result;