-- 🔥 Supabase pg_cron 定时任务设置
-- 在Supabase SQL Editor中执行此脚本

-- 第1步：启用必要的扩展
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS http;

-- 第2步：清理现有的定时任务
DO $$
DECLARE
    job_record RECORD;
BEGIN
    FOR job_record IN SELECT jobname FROM cron.job WHERE jobname LIKE '%rss%' LOOP
        PERFORM cron.unschedule(job_record.jobname);
    END LOOP;
END $$;

-- 第3步：创建定时任务 - 每天上午9点（UTC+8 = UTC 1:00）
-- 任务1: 3D打印RSS抓取
SELECT cron.schedule(
    'fetch-rss-3d-print',
    '0 1 * * *',  -- 每天UTC 1:00 (北京时间9:00)
    $$
    SELECT
        http_post(
            'https://ewjzuiwhvyfmzrmpnzid.supabase.co/functions/v1/fetch-rss',
            '{"rssUrl": "https://news.google.com/rss/search?q=3D+printing&hl=zh-CN&gl=CN&ceid=CN:zh-Hans", "sourceName": "3D Print", "verticalName": "3D打印"}',
            'application/json'
        )
    $$
);

-- 任务2: SEO RSS抓取 (延迟5分钟)
SELECT cron.schedule(
    'fetch-rss-seo',
    '5 1 * * *',  -- 每天UTC 1:05
    $$
    SELECT
        http_post(
            'https://ewjzuiwhvyfmzrmpnzid.supabase.co/functions/v1/fetch-rss',
            '{"rssUrl": "https://news.google.com/rss/search?q=SEO&hl=zh-CN&gl=CN&ceid=CN:zh-Hans", "sourceName": "SEO News", "verticalName": "SEO"}',
            'application/json'
        )
    $$
);

-- 任务3: 农业科技RSS抓取 (延迟10分钟)
SELECT cron.schedule(
    'fetch-rss-agritech',
    '10 1 * * *',  -- 每天UTC 1:10
    $$
    SELECT
        http_post(
            'https://ewjzuiwhvyfmzrmpnzid.supabase.co/functions/v1/fetch-rss',
            '{"rssUrl": "https://news.google.com/rss/search?q=农业机器人&hl=zh-CN&gl=CN&ceid=CN:zh-Hans", "sourceName": "AgriTech", "verticalName": "农业科技"}',
            'application/json'
        )
    $$
);

-- 任务4: 智慧农业RSS抓取 (延迟15分钟)
SELECT cron.schedule(
    'fetch-rss-smart-agriculture',
    '15 1 * * *',  -- 每天UTC 1:15
    $$
    SELECT
        http_post(
            'https://ewjzuiwhvyfmzrmpnzid.supabase.co/functions/v1/fetch-rss',
            '{"rssUrl": "https://news.google.com/rss/search?q=Smart+Agriculture&hl=en&gl=US&ceid=US:en", "sourceName": "Smart Agriculture", "verticalName": "智慧农业"}',
            'application/json'
        )
    $$
);

-- 任务5: 增材制造RSS抓取 (延迟20分钟)
SELECT cron.schedule(
    'fetch-rss-additive-manufacturing',
    '20 1 * * *',  -- 每天UTC 1:20
    $$
    SELECT
        http_post(
            'https://ewjzuiwhvyfmzrmpnzid.supabase.co/functions/v1/fetch-rss',
            '{"rssUrl": "https://news.google.com/rss/search?q=additivemanufacturing&hl=en&gl=US&ceid=US:en", "sourceName": "Additive Manufacturing", "verticalName": "增材制造"}',
            'application/json'
        )
    $$
);

-- 第4步：验证定时任务已创建
SELECT 
    jobname,
    schedule,
    active,
    jobid,
    nodename
FROM cron.job 
WHERE jobname LIKE '%rss%'
ORDER BY jobname;

-- 第5步：查看定时任务执行历史（可选）
-- SELECT * FROM cron.job_run_details WHERE jobname LIKE '%rss%' ORDER BY start_time DESC LIMIT 10;

-- 第6步：创建日志表来跟踪定时任务执行
CREATE TABLE IF NOT EXISTS cron_rss_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name TEXT,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 第7步：手动测试一个定时任务（立即执行）
-- SELECT cron.schedule('test-rss-fetch', '* * * * *', 'SELECT 1;');
-- SELECT cron.unschedule('test-rss-fetch');

-- 完成！
SELECT '🔥 定时任务设置完成！每天上午9点自动抓取RSS源。' as status;